### ISSUE TITLE
Android library can't be built as a sub-module

### ISSUE THREAD

**Issue by sjjhsjjh** [vmware/captive-web-view#14]
I'd like to use Captive Web View for Android as a sub-module under my Android project, instead of by building a local Maven repository.
That doesn't work because, at least, the library web resource assets are included from a directory that is specified in terms of the rootDir. The rootDir is different if the library is included as a sub-module. The specification is near here:
https://github.com/vmware/captive-web-view/blob/main/forAndroid/captivewebview/build.gradle#L19

**Comment by hawkinsji** [comment]
Done.
